#ifndef CONFIG_H
#define CONFIG_H

#define MATH_PI 3.14159

#define WHEEL_RADIUS 1

#define SPI_CS_PIN 10

#define BRAKE_PEDAL A0

#define ACCEL_PEDAL_1 A1

#define ACCEL_PEDAL_2 A2

#define CAN_RATE CAN_500KBPS

#define COMMAND_MESSAGE_ID 0x0C0

#define MAIN_COMMAND_MESSAGE_ID 0x0CD // TODO!

#define MC_INT_STATES_MESSAGE_ID 0x0C0

#define MC_MOTOR_POS_INFO_MESSAGE_ID 0x0A5

#define CALCULATE_CURRENT_QUADRATIC

#define BRAKE_SUBTRACT_COEFF 1

#define BRAKE_MAX_INPUT_VOLTAGE 100500

#define MAX_VOLTAGE_DIFFERENCE 1.0 // ?

#endif
